"""initial schema: cases/investigations/tasks/evidence/entities/relationships/observations/claims/contradictions/audit/model_usage

Revision ID: 92965ba770cb
Revises: 
Create Date: 2026-10-06 14:04:24.816005

"""
revision = '92965ba770cb'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('pk', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('actor', sa.String(length=128), nullable=False),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('detail_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('pk', name=op.f('pk_audit_events'))
    )
    op.create_index(op.f('ix_audit_events_action'), 'audit_events', ['action'], unique=False)
    op.create_index(op.f('ix_audit_events_case_id'), 'audit_events', ['case_id'], unique=False)
    op.create_table('cases',
    sa.Column('pk', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('pk', name=op.f('pk_cases'))
    )
    op.create_index(op.f('ix_cases_case_id'), 'cases', ['case_id'], unique=True)
    op.create_index(op.f('ix_cases_status'), 'cases', ['status'], unique=False)
    op.create_index(op.f('ix_cases_tenant_id'), 'cases', ['tenant_id'], unique=False)
    op.create_table('model_usage',
    sa.Column('pk', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('task_kind', sa.String(length=64), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('pk', name=op.f('pk_model_usage'))
    )
    op.create_index(op.f('ix_model_usage_case_id'), 'model_usage', ['case_id'], unique=False)
    op.create_table('claims',
    sa.Column('pk', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('claim_id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('claim_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], name=op.f('fk_claims_case_id')),
    sa.PrimaryKeyConstraint('pk', name=op.f('pk_claims'))
    )
    op.create_index(op.f('ix_claims_case_id'), 'claims', ['case_id'], unique=False)
    op.create_index(op.f('ix_claims_claim_id'), 'claims', ['claim_id'], unique=True)
    op.create_index(op.f('ix_claims_status'), 'claims', ['status'], unique=False)
    op.create_table('contradictions',
    sa.Column('pk', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contradiction_id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('conflict_type', sa.String(length=32), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('resolution_status', sa.String(length=32), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], name=op.f('fk_contradictions_case_id')),
    sa.PrimaryKeyConstraint('pk', name=op.f('pk_contradictions'))
    )
    op.create_index(op.f('ix_contradictions_case_id'), 'contradictions', ['case_id'], unique=False)
    op.create_index(op.f('ix_contradictions_conflict_type'), 'contradictions', ['conflict_type'], unique=False)
    op.create_index(op.f('ix_contradictions_contradiction_id'), 'contradictions', ['contradiction_id'], unique=True)
    op.create_table('entities',
    sa.Column('pk', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('display_name', sa.String(length=512), nullable=False),
    sa.Column('entity_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], name=op.f('fk_entities_case_id')),
    sa.PrimaryKeyConstraint('pk', name=op.f('pk_entities'))
    )
    op.create_index(op.f('ix_entities_case_id'), 'entities', ['case_id'], unique=False)
    op.create_index(op.f('ix_entities_display_name'), 'entities', ['display_name'], unique=False)
    op.create_index(op.f('ix_entities_entity_id'), 'entities', ['entity_id'], unique=True)
    op.create_index(op.f('ix_entities_kind'), 'entities', ['kind'], unique=False)
    op.create_table('evidence',
    sa.Column('pk', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('evidence_id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('source_slug', sa.String(length=128), nullable=False),
    sa.Column('uri', sa.Text(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('retrieved_at', sa.String(length=64), nullable=False),
    sa.Column('blob_path', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], name=op.f('fk_evidence_case_id')),
    sa.PrimaryKeyConstraint('pk', name=op.f('pk_evidence'))
    )
    op.create_index(op.f('ix_evidence_case_id'), 'evidence', ['case_id'], unique=False)
    op.create_index(op.f('ix_evidence_evidence_id'), 'evidence', ['evidence_id'], unique=True)
    op.create_index(op.f('ix_evidence_sha256'), 'evidence', ['sha256'], unique=False)
    op.create_index(op.f('ix_evidence_source_slug'), 'evidence', ['source_slug'], unique=False)
    op.create_table('investigations',
    sa.Column('pk', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('investigation_id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('stop_reason', sa.String(length=64), nullable=False),
    sa.Column('plan_json', sa.JSON(), nullable=True),
    sa.Column('payload_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], name=op.f('fk_investigations_case_id')),
    sa.PrimaryKeyConstraint('pk', name=op.f('pk_investigations'))
    )
    op.create_index(op.f('ix_investigations_case_id'), 'investigations', ['case_id'], unique=False)
    op.create_index(op.f('ix_investigations_investigation_id'), 'investigations', ['investigation_id'], unique=True)
    op.create_index(op.f('ix_investigations_status'), 'investigations', ['status'], unique=False)
    op.create_table('observations',
    sa.Column('pk', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('observation_id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('evidence_id', sa.String(length=64), nullable=False),
    sa.Column('observation_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], name=op.f('fk_observations_case_id')),
    sa.PrimaryKeyConstraint('pk', name=op.f('pk_observations'))
    )
    op.create_index(op.f('ix_observations_case_id'), 'observations', ['case_id'], unique=False)
    op.create_index(op.f('ix_observations_evidence_id'), 'observations', ['evidence_id'], unique=False)
    op.create_index(op.f('ix_observations_observation_id'), 'observations', ['observation_id'], unique=True)
    op.create_table('relationships',
    sa.Column('pk', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('edge_id', sa.String(length=64), nullable=False),
    sa.Column('case_id', sa.String(length=64), nullable=False),
    sa.Column('src_entity_id', sa.String(length=64), nullable=False),
    sa.Column('dst_entity_id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('relationship_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.case_id'], name=op.f('fk_relationships_case_id')),
    sa.PrimaryKeyConstraint('pk', name=op.f('pk_relationships'))
    )
    op.create_index(op.f('ix_relationships_case_id'), 'relationships', ['case_id'], unique=False)
    op.create_index(op.f('ix_relationships_dst_entity_id'), 'relationships', ['dst_entity_id'], unique=False)
    op.create_index(op.f('ix_relationships_edge_id'), 'relationships', ['edge_id'], unique=True)
    op.create_index(op.f('ix_relationships_kind'), 'relationships', ['kind'], unique=False)
    op.create_index(op.f('ix_relationships_src_entity_id'), 'relationships', ['src_entity_id'], unique=False)
    op.create_table('tasks',
    sa.Column('pk', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('investigation_id', sa.String(length=64), nullable=False),
    sa.Column('wave', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('task_json', sa.JSON(), nullable=False),
    sa.Column('result_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.investigation_id'], name=op.f('fk_tasks_investigation_id')),
    sa.PrimaryKeyConstraint('pk', name=op.f('pk_tasks'))
    )
    op.create_index(op.f('ix_tasks_investigation_id'), 'tasks', ['investigation_id'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_index(op.f('ix_tasks_task_id'), 'tasks', ['task_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_task_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_investigation_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_relationships_src_entity_id'), table_name='relationships')
    op.drop_index(op.f('ix_relationships_kind'), table_name='relationships')
    op.drop_index(op.f('ix_relationships_edge_id'), table_name='relationships')
    op.drop_index(op.f('ix_relationships_dst_entity_id'), table_name='relationships')
    op.drop_index(op.f('ix_relationships_case_id'), table_name='relationships')
    op.drop_table('relationships')
    op.drop_index(op.f('ix_observations_observation_id'), table_name='observations')
    op.drop_index(op.f('ix_observations_evidence_id'), table_name='observations')
    op.drop_index(op.f('ix_observations_case_id'), table_name='observations')
    op.drop_table('observations')
    op.drop_index(op.f('ix_investigations_status'), table_name='investigations')
    op.drop_index(op.f('ix_investigations_investigation_id'), table_name='investigations')
    op.drop_index(op.f('ix_investigations_case_id'), table_name='investigations')
    op.drop_table('investigations')
    op.drop_index(op.f('ix_evidence_source_slug'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_sha256'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_evidence_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_case_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_entities_kind'), table_name='entities')
    op.drop_index(op.f('ix_entities_entity_id'), table_name='entities')
    op.drop_index(op.f('ix_entities_display_name'), table_name='entities')
    op.drop_index(op.f('ix_entities_case_id'), table_name='entities')
    op.drop_table('entities')
    op.drop_index(op.f('ix_contradictions_contradiction_id'), table_name='contradictions')
    op.drop_index(op.f('ix_contradictions_conflict_type'), table_name='contradictions')
    op.drop_index(op.f('ix_contradictions_case_id'), table_name='contradictions')
    op.drop_table('contradictions')
    op.drop_index(op.f('ix_claims_status'), table_name='claims')
    op.drop_index(op.f('ix_claims_claim_id'), table_name='claims')
    op.drop_index(op.f('ix_claims_case_id'), table_name='claims')
    op.drop_table('claims')
    op.drop_index(op.f('ix_model_usage_case_id'), table_name='model_usage')
    op.drop_table('model_usage')
    op.drop_index(op.f('ix_cases_tenant_id'), table_name='cases')
    op.drop_index(op.f('ix_cases_status'), table_name='cases')
    op.drop_index(op.f('ix_cases_case_id'), table_name='cases')
    op.drop_table('cases')
    op.drop_index(op.f('ix_audit_events_case_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_action'), table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
