name: security
on:
  push:
    branches: [main]
  pull_request: {}
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v3
      - run: uv run pip-audit
